#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
export PYTHONPATH=$DIR/:$PYTHONPATH

if [ "$#" -ge 1 ] && [ $1 = 'cuda' ]; then
    COMMAND="THEANO_FLAGS='mode=FAST_RUN,device=cuda,floatX=float32' /usr/bin/env python"
    shift
else
    COMMAND="/usr/bin/env python"
fi

COMMAND="$COMMAND $*"

eval $COMMAND

